Radio:
  error-msg:
    - ""
  permisison: ""
CustomPotions:
Gadgets:
  RedstoneConverter:
    take: "COAL"
    amount: 2
    give: "REDSTONE"
    sound: "BLOCK_NOTE_BLOCK_HAT"
    message: "&2ℹ &nBPG&7 » &7برای تبدیل زغال به رد استون شما به&c %amount% &7عدد زغال نیاز دارید"
  GoldConverter:
    take: "REDSTONE"
    amount: 16
    give: "GOLD_INGOT"
    sound: "BLOCK_NOTE_BLOCK_HARP"
    message: "&2ℹ &nBPG&7 » &7برای تبدیل رد استون به طلا شما به&c %amount%&7 عدد رد استون نیاز دارید"
  EmeraldConverter:
    take: "GOLD_INGOT"
    amount: 8
    give: "EMERALD"
    sound: "BLOCK_NOTE_BLOCK_PLING"
    message: "<dark_green>ℹ <u>BPG</u></dark_green> <gray>»</gray> <gray>برای تبدیل طلا به امرالد شما به</gray> <red>%amount%</red> <gray>عدد طلا نیاز دارید</gray>"
  RepairAnvil:
  Frame:
HitRewards:
  Mythical:
    drop: "REDSTONE"
    amount: 10
    permission: "group.mythical"
  Blaze:
    drop: "REDSTONE"
    amount: 7
    permission: "group.blaze"
  Immortal:
    drop: "REDSTONE"
    amount: 6
    permission: "group.immortal"
  Villain:
    drop: "REDSTONE"
    amount: 5
    permission: "group.villain"
  Elite:
    drop: "REDSTONE"
    amount: 4
    permission: "group.elite"
  magical:
    drop: "REDSTONE"
    amount: 3
    permission: "group.magical"
  Witch:
    drop: "REDSTONE"
    amount: 2
    permission: "group.witch"