Radio:
  error-msg:
    - ""
  permisison: ""
CustomPotions:
Gadgets:
  RedstoneConverter:
    Errors:
      money: "<dark_green>ℹ <u>BPG</u></dark_green> <gray>»</gray> <gray>برای تبدیل زغال به رد استون شما به</gray><red> <amount></red><gray> عدد زغال نیاز دارید</gray>"
    take: "COAL"
    amount: 2
    give: "REDSTONE"
    sound: "BLOCK_NOTE_BLOCK_HAT"
  GoldConverter:
    Errors:
      money: "<dark_green>ℹ <u>BPG</u></dark_green> <gray>»</gray> <gray>برای تبدیل رد استون به طلا شما به</gray><red> <amount></red><gray> عدد رد استون نیاز دارید</gray>"
    take: "REDSTONE"
    amount: 16
    give: "GOLD_INGOT"
    sound: "BLOCK_NOTE_BLOCK_HARP"
  EmeraldConverter:
    Errors:
      money: "<dark_green>ℹ <u>BPG</u></dark_green> <gray>»</gray> <gray>برای تبدیل طلا به امرالد شما به</gray><red> <amount></red><gray> عدد طلا نیاز دارید</gray>"
    take: "GOLD_INGOT"
    amount: 8
    give: "EMERALD"
    sound: "BLOCK_NOTE_BLOCK_PLING"
  RepairAnvil:
    Start:
      sound: "DOOR_CLOSE"
      message: "&2ℹ &nBPG&7 » &a&oدرحال تعمیر...."
    End:
      sound: ""
      message: "&2ℹ &nBPG&7 » &aوسیله ای شما با موفقیت تعمیر شد"
    Errors:
      empty: "&2ℹ &nBPG&7 » &cشما نمیتوانید دست خود را تعمیر کنید!"
      cant: "&2ℹ &nBPG&7 » &cشما نمیتوانید این وسیله را تعمیر کنید"
      already: "&2ℹ &nBPG&7 » &cوسیله شما نیاز به تعمیر ندارد!"
      money: "&2ℹ &nBPG&7 » &cشما برای تعمیر نیاز به 3 طلا دارید."
    take: "GOLD_INGOT"
    amount: 3
    sound: "ANVIL_USE"
    repairableItems:
      - DIAMOND_SWORD
      - IRON_SWORD
      - GOLD_SWORD
      - WOODEN_SWORD
      - STONE_SWORD
      - DIAMOND_AXE
      - DIAMOND_PICKAXE
      - IRON_AXE
      - STONE_AXE
      - BOW
      - DIAMOND_HELMET
      - DIAMOND_CHESTPLATE
      - DIAMOND_LEGGINGS
      - DIAMOND_BOOTS
      - IRON_HELMET
      - IRON_CHESTPLATE
      - IRON_LEGGINGS
      - IRON_BOOTS
      - NETHERITE_HELMET
      - NETHERITE_CHESTPLATE
      - NETHERITE_LEGGINGS
      - NETHERITE_BOOTS
  Frame:
HitRewards:
  Mythical:
    drop: "REDSTONE"
    amount: 10
    permission: "group.mythical"
  Blaze:
    drop: "REDSTONE"
    amount: 7
    permission: "group.blaze"
  Immortal:
    drop: "REDSTONE"
    amount: 6
    permission: "group.immortal"
  Villain:
    drop: "REDSTONE"
    amount: 5
    permission: "group.villain"
  Elite:
    drop: "REDSTONE"
    amount: 4
    permission: "group.elite"
  magical:
    drop: "REDSTONE"
    amount: 3
    permission: "group.magical"
  Witch:
    drop: "REDSTONE"
    amount: 2
    permission: "group.witch"